### ISSUE TITLE
access to the wiki 

### ISSUE THREAD

**Issue by samuncle** [MTres19/stk-docs#2]
Hi thank you very much for having created this repository

I was wondering do you think it would be a good idea to give you a write access to the mediawiki? 

Or at least some articles so you can directly contribute?

**Comment by MTres19** [comment]
I think I have the "Installing the Tools" section pretty much finished. But I'd rather finish the entire thing first and then replace the current pages. That way we could avoid broken links and such.

**Comment by MTres19** [comment]
Actually, I guess I might need wiki access to copy that table. How would I go about creating an account, though? It looks like account creation is disabled...

**Comment by konstin** [comment]
> How would I go about creating an account, though? It looks like account creation is disabled...

That was why samuncle was asking about giving you write access. :wink: It is something only admins can do.

Btw if you're interested you can find the skin and the configuration of the wiki [here](https://github.com/konstin/stk-wiki-theme). Contributions welcome :smile:

**Comment by MTres19** [comment]
Yes, I see now.

Hmmm.... I'm not much an artist, but there were some MediaWiki templates I wanted to create. I might be able to manage that.

**Comment by MTres19** [comment]
Fixed. Thanks, @samuncle.

**Comment by qwertychouskie** [comment]
Still getting:
Permission error

You do not have permission to create this user account, for the following reason:

The action you have requested is limited to users in the group: Administrators.
There is no "edit" button on the pages either.

**Comment by MTres19** [comment]
That's because you're not allowed to create an account. You'll have to ask one of the developers to create one for you.

**Comment by qwertychouskie** [comment]
Oh, OK.  Sounds good.
